### ISSUE TITLE
consider adding other hashing algorithms to README

### ISSUE THREAD

**Issue by bitcoinsSG** [c-geek/merkle#4]
For obvious reasons, there is a lot of interest in blockchain/cryptocurrency space for merkle trees. Most of the the technologies in this space use algorithms with lower collisions and/or higher security than sha1, or md5. Since your module already supports the widely used hashing algorithms such as 'sha256/sha512', because of its usage of the built in crypto library, why not add this to your README file list.

var sha1tree  = merkle('sha1').sync(abcde);
var md5tree   = merkle('md5').sync(abcde);
var cleartree = merkle('none').sync(abcde);
var sha256  = merkle('sha256').sync(abcde);  // Bitcoin
var sha512  = merkle('sha512').sync(abcde);  // Ethereum

**Comment by c-geek** [comment]
I would be very glad you to do it with a pull request, also with a unit test like someone else dit here: https://github.com/c-geek/merkle/commit/f2663c65fe53409aab23bfc1dd9a6fb4648f8f9c

Also, you would have eternal glory of being a contributor of this lib :-)

**Comment by bitcoinsSG** [comment]
done

**Comment by c-geek** [comment]
Thank you!
