### ISSUE TITLE
Resiliency against merkle root malleability 

### ISSUE THREAD

**Issue by bitcoinsSG** [c-geek/merkle#6]
There is a less known vulnerability in merkle tree construction algorithms that affect the merkle root. This vulnerability was in the Bitcoin source code**(1)** (fixed in commit *be8651d*) and as of today, still unresolved in some other repositories for e.g. github.com/chainpoint**(2)**. I think it is important to be cognizant of it as a general rule. I would like to propose that we design a test(s) to protect users of this repository.

1: https://bitcointalk.org/?topic=102395
2: https://github.com/chainpoint/chainpoint/issues/8

**Comment by c-geek** [comment]
I guess this can be closed now.
